{
 "title": "Aplicação TCC",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "company" }
  ]
 },
 "panels": [
  {
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 1, "w": 1, "x": 11, "y": 0 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "firstNotNull",
      "first",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   },
   "targets": [
    { "dataset": "mydb" }
   ]
  },
  {
   "type": "yesoreyeram-boomtheme-panel",
   "gridPos": { "h": 1, "w": 1, "x": 12, "y": 0 },
   "targets": [
    { "dataset": "mydb" }
   ]
  },
  {
   "title": "Porcentagem de Questões Respondidas",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(id_answer) AS \"Respondidos\" FROM mydb.tb_answer WHERE id_company = $company LIMIT 50 "
    }
   ]
  },
  {
   "title": "Porcentagem de Questões Respondidas",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT SUM(weight) FROM mydb.tb_weight join mydb.tb_answer on tb_weight.id_weight = tb_answer.id_answer WHERE tb_answer.id_company = $company"
    }
   ]
  },
  {
   "title": "Total de Respostas por Opção",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(fully_met) AS \"Atende Totalmente\" FROM mydb.tb_answer WHERE tb_answer.id_company = $company AND fully_met = '1' LIMIT 50 "
    },
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(partially_met) AS \"Atende Pacialmente\" FROM mydb.tb_answer WHERE tb_answer.id_company = $company AND partially_met = '1' LIMIT 50 "
    },
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(not_met) AS \"Não Atende\" FROM mydb.tb_answer WHERE tb_answer.id_company = $company AND not_met = '1' LIMIT 50 "
    },
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(not_applicable) AS \"Não Aplicavel\" FROM mydb.tb_answer WHERE tb_answer.id_company = $company AND not_applicable = '1' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total de Evidências Anexadas",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(id_evidence) FROM mydb.tb_evidence join mydb.tb_answer on tb_evidence.id_evidence = tb_answer.id_answer WHERE tb_answer.id_company = $company LIMIT 50 "
    }
   ]
  },
  {
   "title": "5. Controles Organizacionais",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(fully_met) AS \"Atende Totalmente\" FROM mydb.tb_answer WHERE tb_answer.id_company = $company AND (fully_met = '1' AND id_question < '95') "
    },
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(partially_met) AS \"Atende Pacialmente\" FROM mydb.tb_answer WHERE tb_answer.id_company = $company AND ( partially_met= '1' AND id_question < '95') "
    },
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(not_met) AS \"Não Atende\" FROM mydb.tb_answer WHERE tb_answer.id_company = $company AND (not_met = '1' AND id_question < '95') "
    },
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(not_applicable) AS \"Não Aplicavel\" FROM mydb.tb_answer WHERE tb_answer.id_company = $company AND (not_applicable= '1' AND id_question < '95')"
    }
   ]
  },
  {
   "title": "5. Controles Organizacionais - Questões Respondidas",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(id_answer) AS \"Respondidos\" FROM mydb.tb_answer WHERE tb_answer.id_company = $company AND id_question <95"
    }
   ]
  },
  {
   "title": "5. Controles Organizacionais - Pontuação ",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 13, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "select sum(tb_weight.weight) from tb_weight inner join tb_answer on tb_weight.id_weight = tb_answer.id_answer WHERE tb_answer.id_company = $company AND tb_answer.id_question < 95;"
    }
   ]
  },
  {
   "title": "5. Controles Organizacionais - Evidências Anexadas",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(tb_evidence.id_evidence) FROM tb_evidence inner join tb_answer on tb_evidence.id_evidence = tb_answer.id_answer WHERE tb_answer.id_company = $company AND tb_answer.id_question < 95; "
    }
   ]
  },
  {
   "title": "6. Controles de pessoas",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(fully_met) AS \"Atende Totalmente\" FROM mydb.tb_answer WHERE tb_answer.id_company = $company AND (fully_met = '1' AND id_question > '94' and id_question < '136') "
    },
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(partially_met) AS \"Atende Pacialmente\" FROM mydb.tb_answer WHERE tb_answer.id_company = $company AND ( partially_met= '1' AND id_question > '94' and id_question < '136') "
    },
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(not_met) AS \"Não Atende\" FROM mydb.tb_answer WHERE tb_answer.id_company = $company AND (not_met = '1' AND id_question > '94' and id_question < '136')"
    },
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(not_applicable) AS \"Não Aplicavel\" FROM mydb.tb_answer WHERE tb_answer.id_company = $company AND (not_applicable= '1' AND id_question > '94' and id_question < '136')"
    }
   ]
  },
  {
   "title": "6. Controles de pessoas - Questões Respondidas",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 6, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(id_answer) AS \"Respondidos\" FROM tb_answer WHERE tb_answer.id_company = $company AND (id_question > '94' and id_question < '136')"
    }
   ]
  },
  {
   "title": "6. Controles de pessoas - Pontuação ",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 13, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "select sum(tb_weight.weight) from tb_weight inner join tb_answer on tb_weight.id_weight = tb_answer.id_answer WHERE tb_answer.id_company = $company AND (tb_answer.id_question > '94' and tb_answer.id_question < '136');"
    }
   ]
  },
  {
   "title": "6. Controles de pessoas - Evidências Anexadas",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(tb_evidence.id_evidence) FROM tb_evidence inner join tb_answer on tb_evidence.id_evidence = tb_answer.id_answer WHERE tb_answer.id_company = $company AND (tb_answer.id_question > '94' and tb_answer.id_question < '136'); "
    }
   ]
  },
  {
   "title": "7. Controles físicos",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(fully_met) AS \"Atende Totalmente\" FROM mydb.tb_answer WHERE tb_answer.id_company = $company AND (fully_met = '1' AND id_question > '135' and id_question < '203') "
    },
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(partially_met) AS \"Atende Pacialmente\" FROM mydb.tb_answer WHERE tb_answer.id_company = $company AND ( partially_met= '1' AND id_question > '135' and id_question < '203') "
    },
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(not_met) AS \"Não Atende\" FROM mydb.tb_answer WHERE tb_answer.id_company = $company AND (not_met = '1' AND id_question > '135' and id_question < '203')"
    },
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(not_applicable) AS \"Não Aplicavel\" FROM mydb.tb_answer WHERE tb_answer.id_company = $company AND (not_applicable= '1' AND id_question > '135' and id_question < '203')"
    }
   ]
  },
  {
   "title": "7. Controles físicos - Questões Respondidas",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 6, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(id_answer) AS \"Respondidos\" FROM mydb.tb_answer WHERE tb_answer.id_company = $company AND (id_question > '135' and id_question < '203')"
    }
   ]
  },
  {
   "title": "7. Controles físicos - Pontuação ",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 13, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "select sum(tb_weight.weight) from tb_weight inner join tb_answer on tb_weight.id_weight = tb_answer.id_answer WHERE tb_answer.id_company = $company AND (tb_answer.id_question > '135' and tb_answer.id_question < '203');"
    }
   ]
  },
  {
   "title": "7. Controles físicos - Evidências Anexadas",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(tb_evidence.id_evidence) FROM tb_evidence inner join tb_answer on tb_evidence.id_evidence = tb_answer.id_answer WHERE tb_answer.id_company = $company AND (tb_answer.id_question > '135' and tb_answer.id_question < '203'); "
    }
   ]
  },
  {
   "title": "8. Controles tecnológicos",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(fully_met) AS \"Atende Totalmente\" FROM mydb.tb_answer WHERE tb_answer.id_company = $company AND (fully_met = '1' AND id_question > '202' and id_question < '320') "
    },
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(partially_met) AS \"Atende Pacialmente\" FROM mydb.tb_answer WHERE tb_answer.id_company = $company AND ( partially_met= '1' AND id_question > '202' and id_question < '320') "
    },
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(not_met) AS \"Não Atende\" FROM mydb.tb_answer WHERE tb_answer.id_company = $company AND (not_met = '1' AND id_question > '202' and id_question < '320')"
    },
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(not_applicable) AS \"Não Aplicavel\" FROM mydb.tb_answer WHERE tb_answer.id_company = $company AND (not_applicable= '1' AND id_question > '202' and id_question < '320')"
    }
   ]
  },
  {
   "title": "8. Controles tecnológicos - Questões Respondidas",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 6, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(id_answer) AS \"Respondidos\" FROM tb_answer WHERE tb_answer.id_company = $company AND (id_question > '202' and id_question < '320')"
    }
   ]
  },
  {
   "title": "8. Controles tecnológicos - Pontuação ",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 13, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "select sum(tb_weight.weight) from tb_weight inner join tb_answer on tb_weight.id_weight = tb_answer.id_answer WHERE tb_answer.id_company = $company AND (tb_answer.id_question > '202' and tb_answer.id_question < '320');"
    }
   ]
  },
  {
   "title": "8. Controles tecnológicos - Evidências Anexadas",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT COUNT(tb_evidence.id_evidence) FROM tb_evidence inner join tb_answer on tb_evidence.id_evidence = tb_answer.id_answer WHERE tb_answer.id_company = $company AND (tb_answer.id_question > '202' and tb_answer.id_question < '320'); "
    }
   ]
  }
 ]
}