# database configs
spring.datasource.url=jdbc:mysql://localhost:3306/mydb?useTimezone=true&serverTimezone=America/Sao_Paulo
spring.datasource.username=fatec
spring.datasource.password=fatec@123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# token
api.security.token.secret=$3cr3T_KeY_TCC_AuDiT_T3$t_$3CUritY

spring.servlet.multipart.max-file-size=55429081B
spring.servlet.multipart.max-request-size=55429081B

server.servlet.context-path=/tcc-audit
